### ISSUE TITLE
Anyone looking at pull requests?

### ISSUE THREAD

**Issue by smrama** [microsoft/Application-Insights-K8s-Codeless-Attach#60]
Hi Team,

I have raised a pull request for a fix to an incorrect namespace. I am new and hence I dont know the process to follow for adding reviewers. Unfortunately I could not add anyone. If someone is looking through issues, please approve and merge the pull request.

Best regards

**Comment by tokaplan** [comment]
@smrama please be advised that this project is not supported any more, and hasn't been for a while. With that in mind, if you'd like to contribute still, I'll gladly merge the PR for you.

**Comment by smrama** [comment]
Hi @tokaplan,

Thank you for approving the PR. I would like to contribute to this code base as this is very useful to inject the AppInsights JAR instead of packaging via Maven or Gradle.

Please merge the PR and add me as maintainer if possible.

Thank you.

**Comment by tokaplan** [comment]
PR merged, I've added you to the project. Thank you!
